//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_21_Kiko
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lab_21Entities : DbContext
    {
        public Lab_21Entities()
            : base("name=Lab_21Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static Lab_21Entities context;
        public static Lab_21Entities GetContext()
        {
            if (context == null) context = new Lab_21Entities();
            return context;
        }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Объём_работ_на_объекте> Объём_работ_на_объекте { get; set; }
        public virtual DbSet<связб> связб { get; set; }
        public virtual DbSet<Справочник_видов_работ> Справочник_видов_работ { get; set; }
        public virtual DbSet<Справочник_окончани_работ> Справочник_окончани_работ { get; set; }
        public virtual DbSet<Справочник_расценок> Справочник_расценок { get; set; }
        public virtual DbSet<Справочник_строительных_объектов> Справочник_строительных_объектов { get; set; }
    }
}
