//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_21_Kiko
{
    using System;
    using System.Collections.Generic;
    
    public partial class Справочник_строительных_объектов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Справочник_строительных_объектов()
        {
            this.Объём_работ_на_объекте = new HashSet<Объём_работ_на_объекте>();
        }
    
        public int Код_объекта { get; set; }
        public string Наименование_объекта { get; set; }
        public string Населенный_пункт { get; set; }
        public string Адрес_объекта { get; set; }
        public Nullable<System.DateTime> Дата_начала_работ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Объём_работ_на_объекте> Объём_работ_на_объекте { get; set; }
        public virtual Справочник_окончани_работ Справочник_окончани_работ { get; set; }
    }
}
